# ------------------------------------------------------------------------------
# Trivadis - Part of Accenture, Platform Factory - Transactional Data Platform
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# ------------------------------------------------------------------------------
# Name.......: output.tf
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2021.11.17
# Revision...: 
# Purpose....: Outputs defined for the terraform configuration.
# Notes......: --
# Reference..: --
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# ------------------------------------------------------------------------------
# display the VCN IDs
output "vcn_id" {
  description = "id of VCNs which are created"
  value       = module.tvdlab-vcn.vcn_id
}

### Important Security Notice ###
# The private key generated by this resource will be stored unencrypted in your Terraform state file. 
# Use of this resource for production deployments is not recommended. 
# Instead, generate a private key file outside of Terraform and distribute it securely to the system where Terraform will be run.
output "generated_private_key_pem" {
  value     = tls_private_key.bastion_ssh_key.private_key_pem
  sensitive = true
}

output "generated_guacamole_password" {
  value     = local.guacadmin_password
  sensitive = true
}

output "generated_tvd_password" {
  value     = local.tvd_def_password
  sensitive = true
}

output "lab_website_url" {
  value = join("/", ["http:/", var.webproxy_name, local.resource_name_lower])
}

# display public IPs of bastion hosts
output "bastion_public_ip" {
  description = "The public IP address of the bastion server instances."
  value       = module.tvdlab-bastion.bastion_public_ip
}

output "bastion_private_ip" {
  description = "The private IP address of the bastion server instances."
  value       = module.tvdlab-bastion.bastion_private_ip
}

output "bastion_hostname" {
  description = "The hostname for VNIC's primary private IP of the bastion server instances."
  value       = module.tvdlab-bastion.bastion_hostname
}

output "bastion_ssh_access" {
  description = "SSH access string for bastion hosts."
  value       = module.tvdlab-bastion.bastion_ssh_access
}

output "bastion_public_url" {
  description = "Bastion Apache Guacammole URL."
  value       = module.tvdlab-bastion.bastion_public_url
}

output "public_key_openssh" {
  description = "Bastion public key openssh."
  value       = tls_private_key.bastion_ssh_key.public_key_openssh
}

output "private_key_pem" {
  description = "Bastion private key openssh."
  value       = tls_private_key.bastion_ssh_key.private_key_pem
  sensitive   = true
}
# --- EOF ----------------------------------------------------------------------
